coreos/fedora-coreos-tracker

- PRD.txt
As discussed in the meeting, some clustering specific support will be needed for the 'Clustered server node' use case; locksmith for example.  Also, although I try my best, I sometimes mess things up, and so I think we should be able send out fixes for critical bugs.
> PRD: Update cluster node, out-of-cycle updates

- Design.md
Accidently `git push -d` instead of `git push -f` on the other PR, which made it unopenable.
Please check for:
-  Grammar, clarity, etc
-  That I accurately recorded the discussion
-  Formatting seems good
I only did the partitioning issue. We can add summaries of other closed issues in more PRs.
I envision that when we want to close out an issue, we PR this doc with a summary. Once we agree the PR is good and accurately encapsulates the discussion, we merge the PR and close the issue.
As the doc grows we may want to break it out into multiple docs in a directory, but that can come later.
Finally, I'd prefer to keep this doc about design of FCOS itself and not about the process around it. We can have a seperate doc for that (the README does a great job right now) if we want.
> design doc: add design doc

- README.md
We don't actually do this, so make the docs match reality.
> README: don't include full meeting log in minutes email

- Design.md
Adds design decisions from #65 & #97.
> design: add azure section to cloud agents

- Design.md
> design: add aws section to cloud agents

- Design.md
Add design decisions from #71.
> design: add DigitalOcean section to cloud agents

- Design.md
> design: add Packet section to cloud agents

- Design.md
> design: add no-autologin policy

- Design.md
Addresses https://github.com/coreos/fedora-coreos-tracker/issues/129
Closes https://github.com/coreos/fedora-coreos-tracker/issues/89
> Design: Add section on FCC/FCCT/FCCL

- Design.md
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/181.
> design: automatically disable SMT when vulnerable

- Design.md
> design: add bucket layout

- Design.md
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/81.  Fixes https://github.com/coreos/fedora-coreos-tracker/issues/211.
> Design: add version numbering scheme

- metadata/README.md
- metadata/release-index/specifications.md
This adds a human-friendly specification describing the semantics of
the release-index document.
> metadata/release-index: add human-friendly specs

- metadata/README.md
- metadata/updates/specifications.md
This adds a human-friendly specification describing the semantics of
the updates metadata.
> metadata/updates: add human-friendly specs

- metadata/README.md
- metadata/release-index/fcos-release-index-schema.json
This adds a JSON schema for the release-index.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/206
> metadata: add release-index JSON schema

- metadata/updates/fcos-updates-schema.json
- metadata/updates/sample.json
- metadata/updates/specifications.md
This fixes the `start_percentage` range, properly capping it at `1.0`.
> metadata/updates: fix range

- README.md
This is simply fixing a markdown link that was missing the initial `[` character.
> Fix papercuts board link in main README.md

- README.md
- RELEASES.md
Add basic short information about FCOS releases, with links to the more
in-depth design document.
Also add a link to the HackMD release schedule.
> Add RELEASES.md

- NEWPACKAGE.md
- README.md
An initial set of instructions on how to request a new package be
added to FCOS. This can be folded into a chooser option for new
issues, if desired.
Closes #641
> instructions for requesting new packages

- internals/README-initramfs.md
This documents the design in #460 with some more implementation details.
This came up in discussions today while talking about #689, so let's
write it down somewhere so it's easier to reference in the future.
Closes: #460
> README-initramfs.md: add section about networking

- docs/ci-and-builds.md
Trying to migrate content from https://github.com/coreos/fedora-coreos-tracker/issues/764
which is a proposal into a "how it works" that we can maintain over time.
> docs/ci-and-builds.md: Overview of CI and FCOS pipeline

- .github/ISSUE_TEMPLATE/rebase.md
Based on the [fedora-coreos-config README](https://github.com/coreos/fedora-coreos-config/blob/da55a2e50c2d/README.md#moving-to-a-new-major-version-n-of-fedora).
> templates: add checklist for rebasing to a new version of Fedora

- metadata/stream/rationale.yaml
This doesn't bring the rationale completely up to date with current reality (it's missing some platforms, and lists some cloud images we don't ship yet) but it's closer.
> stream/rationale: several cleanups

- metadata/stream/rationale.yaml
The artifact format was wrong, and `uncompressed-sha256` is added by coreos/coreos-assembler#2144.
> stream/rationale: more DigitalOcean fixes

- internals/README-internals.md
Came up in post-commit review that we do support user units
dispatching on this.
> docs/internals: Link to main docs for ignition.platform.id

- .github/ISSUE_TEMPLATE/rebase.md
https://github.com/coreos/butane/pull/248 switches the Butane container build to Fedora, and Ignition is already there.
> templates/rebase: add Ignition and Butane containers

- internals/README-initramfs.md
`ignition-setup-base` is gone (Ignition handles it internally now) and `ignition-setup-user` has moved to fedora-coreos-config and renamed to `coreos-ignition-setup-user`.
xref https://github.com/coreos/fedora-coreos-config/pull/1095
> internals/initramfs: update for coreos-ignition-setup-user

- internals/README-initramfs.md
I guess you've got the Markdown syntax "wrong" here and want a line break here. :slightly_smiling_face:
> Add missing line break in internal Markdown docs

- .github/ISSUE_TEMPLATE/rebase.md
from coreos-installer.
cc @dustymabe
> templates/rebase: drop image signing key for previous release

- metadata/stream/rationale.yaml
- metadata/stream/sample.json
It's useful to record the exact software version that generated an instance of stream metadata.
> metadata/stream: add metadata.generator field

- README.md
GitHub does not render non-HTTP URLs so use Libera.Chat webchat instead.
> README: Update IRC URL & add matrix.to link for Matrix

- .github/ISSUE_TEMPLATE/rebase.md
It's going away in https://github.com/coreos/coreos-assembler/pull/2550.
This reverts #1015.
> Revert "templates: update link to buildroot Dockerfile"

- .github/ISSUE_TEMPLATE/rebase.md
https://github.com/coreos/fedora-coreos-pipeline/pull/451 adds a centralized mechanism for disabling the `next-devel` stream.  Use it during a rebase.
> templates/rebase: disable `next-devel` using pipeline metadata

- Design.md
Make `testing` release with GA content on week 0 as discussed in
https://github.com/coreos/fedora-coreos-tracker/issues/1024.
Closes: #1024
> Design.md: tweak Fedora GA rebase schedule

- .github/ISSUE_TEMPLATE/rebase.md
Let's tag in a package into the continuous tag so that the initial
distrepo task will kick off and the yum repo will exist when the first
brave souls try to build COSA against the next major version of Fedora.
> templates/rebase: creating initial f${N+1}-coreos-continuous yum repo

- metadata/stream/rationale.yaml
We ended up splitting the image reference into its parts, and including both the image family name and the specific image it currently points to.
> metadata/stream/rationale: update GCP to match current metadata

- metadata/stream/rationale.yaml
Update docs to include KubeVirt.
xref #1126
> Add KubeVirt to rationale.yaml

- metadata/stream/rationale.yaml
In the current design, the KubeVirt image is presumed to be a pull spec with an image digest.  That implies that the user should reference the image by digest, when we'd prefer that they reference it by a stream-specific floating tag.
Define the existing `image` field to contain a pull spec with a floating tag for the stream.  We should still record the unique identifier of the current image (as we do for GCP images), so add a `digest-ref` field which always contains a fully-qualified pull spec with digest.
xref https://github.com/coreos/stream-metadata-go/pull/46
cc @rmohr @dustymabe
> metadata/stream: add digest reference to KubeVirt image description

- .github/ISSUE_TEMPLATE/rebase.md
These tickets help us stay up on various release processes and
changes. Let's formalize them in our toplevel rebase tracker template.
> templates/rebase: add instructions for creating tracker tickets

- metadata/release/sample.json
- metadata/stream/rationale.yaml
- metadata/stream/sample.json
To have a complete representation of the artifacts we support in the
stream metadata sample,rationale & release, the FCOS stream metadata sample/
rationale/release have been updated with the missing platforms.
Resolves : https://issues.redhat.com/browse/COS-1364
> Updated FCOS stream metadata sample/rationale/release

- meeting-people.txt
Added myself to the list. 
I am a primarily a matrix user so I was wondering if I should use `anthr76[m]` but I think this should work.
> Add anthr76 to meeting-people.txt

- .github/workflows/checks.yml
Fixes [deprecation warnings](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) for Node.js 12.
> workflows: update actions to current major versions

- .github/ISSUE_TEMPLATE/bug-report.yml
Users often post Butane configs rather than Ignition configs, and JSON is upward-compatible with YAML, so cover our bases by calling it YAML. This prevents the user from having to manually add a code block.  Explicitly label the field as "Butane or Ignition config".
> templates: format bug-report Ignition config as YAML

- .github/ISSUE_TEMPLATE/rebase.md
```
commit de41d0db47e2d0a420f9dbcc5d837181f9415716
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Wed May 3 14:56:54 2023 -0400
templates/rebase: move "Untag old packages" section later
This doesn't need to happen until the end which is usually the best
place for cleanups anyway. Let's move it later.
commit 5bea275219350a12c0269eb72b02b299fa3724ee
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Wed May 3 14:39:45 2023 -0400
templates/rebase: Remove 'Disable `branched` stream' section
This should have been removed in fd62a94 when a step for this was added
to another section.
```
> templates/rebase: move one section; delete another

- .github/ISSUE_TEMPLATE/rebase.md
```
commit 46fcf448dc2ec5ce9a4969b71b3106f2e878fd73
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Mon May 22 10:16:52 2023 -0400
templates/rebase: additional container update steps
- We refactored coreos-cincinnati a bit to look more like the other Apps
so let's add steps here for updating it.
- Add fedora-ostree-pruner to the list since that's now running in
production too.
commit d7b51ed1c42cd2d5c9aacfafaeffc11e01b01725
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Mon May 22 10:15:58 2023 -0400
templates/rebase: add -v to `koji untag-build`
This will give you some status updates to the screen while it's running.
Otherwise there's not much feedback to the user and you aren't sure if
it's working or not.
commit a6a9654769e5ce96ce551d647378ae81552d9853
Author: Dusty Mabe …
```
> templates/rebase: more updates from recent experience

- metadata/release/sample.json
- metadata/stream/rationale.yaml
- metadata/stream/sample.json
Add example metadata for new platform support of hyperv. This supports:
* https://github.com/coreos/fedora-coreos-tracker/issues/1411
* https://github.com/coreos/fedora-coreos-tracker/issues/1424
> Add Hyper-V metadata

- .github/ISSUE_TEMPLATE/new-feature.md
Propose a process checklist for implementing a new feature, along with an initial list of potential complications to think about.
This may not be universally accepted or widely used.  But, I had some process notes sitting around, and maybe they'll be useful as a starting point.
> templates: add new-feature template

- README.md
- docs/ci-and-builds.md
We'd like to direct all communications to the Matrix channel going
forward, so let's drop mentions of the IRC channel.
Related: #1566
> Only mention Matrix channel as chat room

- .github/ISSUE_TEMPLATE/implementing-new-emerging-platform.md
- .github/ISSUE_TEMPLATE/implementing-new-platform.md
Add a new template that does not include all the steps to generate boot images.
This will help adding new platforms to Fedora CoreOS without imposing an ever increasing burden on our release pipeline and cloud storage by creating more (mostly) duplicated boot images.
> Issue template: Add a "new platform light" template

- .github/ISSUE_TEMPLATE/rebase.md
templates/rebase: document adding/removing `fedora-candidate-compose` repo
This is a repo that we only want during the Beta period. Make sure we
remove it otherwise.
Closes: #1602
---
templates/rebase: document final `next` release before GA
This is what we do in practice but it wasn't documented.
> templates/rebase: various tweaks from current walk-through

- .github/ISSUE_TEMPLATE/rebase.md
- Design.md
templates/rebase: mention that testing GA release is promoted from next
---
templates/rebase: clarify `testing` release staging
Make a separate step for staging the `testing` build and releasing it
since that's what we actually do in practice.
> templates/rebase: more tweaks from current walk-through

- README.md
With the addition of the new repo for creating dynamic fcos meeting checklists, update readme to mention its location, and make old meeting notes legacy, and minimized.
> readme: update meeting notes

- metadata/release/sample.json
- metadata/stream/rationale.yaml
- metadata/stream/sample.json
Add new platform (applehv) for the Apple Hypervisor which uses the raw disk format.
See coreos/fedora-coreos-tracker#1533 and coreos/fedora-coreos-tracker#1548
> Update FCOS stream metadata for Apple Hypervisor

- .github/ISSUE_TEMPLATE/rebase.md
Add some useful links to locate the Fedora (N+1) signing keys to assist with this step in the future.
> template/rebase: add more info about updating signing keys

- meeting-people.txt
We are automating this now with
https://github.com/coreos/fcos-meeting-action/pull/83 so we have no need for the instructions.
> Remove command from meeting-people.txt

- .github/ISSUE_TEMPLATE/rebase.md
Since we moved some containers that kola relied on to the coreOS pipeline, let's update the base image as well
I added it manually in https://github.com/coreos/fedora-coreos-tracker/issues/1674
> Rebase checklist: add Containerfiles for kola containers

- .github/ISSUE_TEMPLATE/rebase.md
Add a step to the Fedora Rebase Checklist to update the Fedora version in the RHCOS extensions container Dockerfile.
We recently ran into a situation where the version hadn't been updated and it caused us some issues. 
See: https://github.com/openshift/os/pull/1545 and https://github.com/openshift/os/pull/1550.
https://github.com/openshift/os/issues/1546 aims to move away from using Fedora images for RHCOS and SCOS, so we may be able to remove this step in the future.
> templates/rebase: add rhcos extensions container update step

- .github/ISSUE_TEMPLATE/rebase.md
This will ensure our test containers that get used are updated to latest Fedora N regularly.
> add container bump step to rebase tracker

- README.md
the coreos tag in discourse is not used anymore.
Instead we are using the coreos-wg tag
> Update Discourse tag
