- Design.md
Discussion from:
https://github.com/coreos/fedora-coreos-tracker/issues/23
> design: Add in OSTree delivery format results

- README.md
The link to the discussion category changed.
> README: fix URL

- Design.md
> design: add openstack section to cloud agents

- Design.md
This summarizes firewalling directions, as discussed in
https://github.com/coreos/fedora-coreos-tracker/issues/26
> design: add section on firewall management

- README.md
- README: fix hyperlink
- README: fix spelling error
> A few cosmetic fixes

- Design.md
https://github.com/coreos/fedora-coreos-tracker/issues/162
> Design: GCE -> GCP

- metadata/stream.yaml
cincinnati may require additional information for updates policy.
Let's first finalize all needed information and add Updates field
in stream metadata
> Remove updates from stream until we finalize what cincinnati needs

- Design.md
To clarify there's no `/var` by default, etc.
> design: Rework partition proposal

- metadata/README.md
- metadata/updates/fcos-updates-schema.json
This adds a JSON schema for the updates metadata.
Ref: #206
> metadata: add updates metadata JSON schema

- metadata/release/sample.json
- metadata/stream/sample.json
> Add sample release and stream metadata for aliyun and azure

- internals/README-internals.md
Imported from https://hackmd.io/0e_oup-qTLeO77k_DfwdTA
The idea is this is a quick place to dump links/discussion
about internals.
> README-internals.md: New doc

- internals/README-initramfs.md
- internals/README-internals.md
Co-authored with other people on the CoreOS team via hackmd.io.
> Add README-initramfs.md

- meeting-people.txt
I've added myself [nasirhm] in the meeting people in order to get notified for the meeting.
> Addition of nasirhm in Meeting people.

- internals/README-initramfs.md
Let's write this down somewhere since it comes up once in a while and
it's important to be aware of all the services that do this and when
they run.
> internals: document units that mount /boot in the initrd

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/requesting-new-package.md
I took a guess at what would be good for the bug report template.  The new package template is taken from #655.
> Bug Report + New Package templates

- .github/ISSUE_TEMPLATE/new-platform.md
Requestors are unlikely to have all this information up front, but it'd be good to document what information we need and have a centralized place to collect it.
cc @arithx @darkmuggle @dustymabe @jlebon @lucab
> templates: add template for requesting a new platform

- metadata/README.md
Let's make it easier to piece together the awesome Rube Goldberg
series of JSON transformations that take a cosa build to a stream.
> metadata: Link to projects/code, also note coreos-assembler

- meeting-people.txt
> Add PanGoat

- docs/20210204_fcos_official_edition.md
- docs/20210204_growing_fcos_community.md
During the CoreOS Virtual F2F, we held two sessions open to the
community to discuss:
- Growing the Fedora CoreOS Community
- Making Fedora CoreOS an Official Fedora Edition
This captures the HackMD contents from those two sessions.
> add minutes from FCOS community sessions

- internals/README-initramfs.md
This was missing the bit about how Afterburn fits into the picture.
> internals/initramfs: add more details about networking

- .github/ISSUE_TEMPLATE/rebase.md
> templates: create sub-list for pool untagging; skip update barriers for now

- metadata/stream/rationale.yaml
- metadata/stream/sample.json
See https://github.com/coreos/stream-metadata-go/pull/11
> metadata: Add uncompressed-sha256

- internals/README-internals.md
I want to link to this from https://github.com/cgwalters/coreos-diskimage-rehydrator
> internals: Talk about ignition.platform.id

- internals/README-internals.md
Let's collate information on this.
> internals: Talk about multipath

- .github/ISSUE_TEMPLATE/rebase.md
This fixes up the formatting a bit.
> templates: replace tabs with spaces in rebase template

- meeting-people.txt
> meeting-people: Add jcajka

- .github/workflows/checks.yml
- meeting-people.txt
Robots reviewing code > humans reviewing code.
> workflows: verify that meeting-people.txt is sorted

- metadata/stream/sample.json
For https://github.com/coreos/stream-metadata-go/pull/36.
> metadata/stream/sample: add release field for GCP

- README.md
See: https://discussion.fedoraproject.org/t/fedora-discussion-2022-whats-new/35558
> README: Update forum URL

- .github/ISSUE_TEMPLATE/rebase.md
This reorganizes the structure a bit so that items are organized more
based on when they should happen. It also adds various elements that
were missing before that happened to come to me as I was re-organizing
things.
> template: update rebase issue template

- internals/README-initramfs.md
This came up in discussion today. Let's document some of the internal
details because multipath support is not straightforward.
> internals/README-initramfs: add some info about multipath

- .github/ISSUE_TEMPLATE/implementing-new-platform.md
Starting to put together documentation around the steps required for adding a new platform. https://github.com/coreos/fedora-coreos-tracker/issues/675
> add documentation for adding a new platform

- docs/fedora-coreos-kernel-bisect.md
Requires https://github.com/coreos/fedora-coreos-config/pull/1935
> docs: updates for kernel bisect docs

- metadata/release/sample.json
- metadata/stream/rationale.yaml
- metadata/stream/sample.json
Add the secure execution artifact to the stream and release examples.
> Update stream metadata sample/rationale for secure execution

- .github/ISSUE_TEMPLATE/implementing-new-platform.md
Mention Ignition, Afterburn, and `platforms.yaml`.  Update the build pipeline step for pipeline changes.  Clean up formatting.
> templates/implementing-new-platform: add some steps; reformat

- metadata/release/sample.json
- metadata/stream/rationale.yaml
- metadata/stream/sample.json
Updating the format for kubevirt artifacts in `rationale.yaml` and `sample.json` for streams and releases metadata.
> Update kubevirt artifact's format

- README.md
See: https://github.com/coreos/fedora-coreos-tracker/pull/1322
> README: Update link to new package request issue

- meeting-people.txt
> meeting-people: remove skunkerk

- docs/fedora-coreos-kernel-bisect.md
+ Update latest kernel verion
+ Update fedora:38
> update version bump

- meeting-people.txt
Add myself to meeting-people.txt to receive notifications about Fedora CoreOS community meetings.
> Add ydesouza to meeting-people.txt

- README.md
- meeting-people.txt
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/1616
> README: Update for Matrix based meetings

- README.md
See: https://github.com/coreos/fedora-coreos-tracker/issues/1616
> README: Matrix to Libera Chat bridge shutdown

- .github/ISSUE_TEMPLATE/rebase.md
This will help people going through this see what the change should look like.
> template/rebase: add a bunch more example PR links

- meeting-people.txt
I'd like to get pinged when the CoreOS meetings are happening 😄
> Add yves:siegrist.io to be notified when meetings happen

- metadata/release/sample.json
- metadata/stream/rationale.yaml
- metadata/stream/sample.json
https://github.com/coreos/fedora-coreos-tracker/issues/1874
> metadata: add examples for hetzner

- meeting-people.txt
Add @tlbueno:fedora.im to meeting-people.txt to get notification about next meetings
> Add @tlbueno:fedora.im to meeting-people.txt

- README.md
- metrics/README.md
- metrics/fcos-sqlitevis.json
And also generate charts using a tool called sqlitevis.
> add info on how to view metrics

- metadata/release/sample.json
- metadata/stream/rationale.yaml
- metadata/stream/sample.json
https://github.com/coreos/fedora-coreos-tracker/issues/1967
> metadata: add examples for oraclecloud
